version: "2.1"

networks:
  tools:

volumes:
  jenkins_home:
    name: jenkins_home
  nexus-data:
    name: nexus-data


services:
# something did not work out with nginx - skipping it for now
#  nginx:
#    build: nginx
#    ports:
#      - 8080:8080
#      - 443:443
#    networks:
#      - tools
  jenkins:
    build: jenkins
    ports:
      - 8081:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 133 #docker group id
    networks:
      - tools
  tomcat:
    build: tomcat
    ports:
      - 8082:8080
    networks:
      - tools
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - 8083:8081
    networks:
      - tools
    volumes:
      - nexus-data:/nexus-data
  sonaqube:
    image: sonarqube:latest
    ports:
      - 8084:9000
    networks:
      - tools

